language: node_js
node_js:
  - node

cache:
  directories:
    - "node_modules"

before_install:
  - make vendor

install:
  - npm install

before_script:
  - npm run lint

script:
  - npm run build

after_success:
  - npm run test
  - bash <(curl -s https://codecov.io/bash)
